### ISSUE TITLE
Newton Support

### ISSUE THREAD

**Issue by bottkars** [emc-openstack/unity-cinder-driver#2]
Hello,
i can not find a Newton Branch here.
When will it be available ?

**Comment by peter-wangxu** [comment]
Hi @bottkars 

Please refer to https://github.com/emc-openstack/unity-cinder-driver/issues/1#issuecomment-261833822 and https://github.com/emc-openstack/unity-cinder-driver/issues/1#issuecomment-261856589 for how to bring up the unity driver for Newton

**Comment by peter-wangxu** [comment]
@bottkars newton branch is ready for use now.
https://github.com/emc-openstack/unity-cinder-driver/tree/newton
