### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by emil-jacero** [emc-openstack/unity-cinder-driver#50]
Hi,

Looking at the releases, tags and branches i was a little bit confused of what is latest and what is old.
Version 5.x.x doesn't seem to have a tag. What is the reason for that?
I was also unable to find a branch for Stein does that mean Stein is not supported?

Thanks in advance :)

**Comment by yong-huang** [comment]
Hi,

Please ignore the tags and releases in this repo, they are no longer be used now.
The branches are mapping to the OpenStack releases, for example, the rocky branch is mapping to OpenStack Rocky release.

The version like 5.x.x defined in driver.py is the driver's version, 5.x.x is mapping to OpenStack Stein release.

This repo is used to store the "Downstream" driver. It is controlled by ourselves, not by the OpenStack community, we could backport some features, bug fixes easily even if the releases already EOL (Newton, Mitaka, etc..).
There are no customized features/bug fixes backport for Stein, so we never create the stein branch till now, you could get the Stein version driver from the OpenStack community repo: https://github.com/openstack/cinder/tree/stable/stein/cinder/volume/drivers/dell_emc/unity

Thanks

**Comment by emil-jacero** [comment]
Hi,

Thank you for the answer!
