### ISSUE TITLE
'UnityDriver' object has no attribute 'accept_transfer'

### ISSUE THREAD

**Issue by lucker6666** [emc-openstack/unity-cinder-driver#6]
on Mirantis 9.2 - Mitaka version, using unity driver met below error

<155>Apr  1 07:59:32 node-3 cinder-api: 2017-04-01 07:59:32.304 7413 ERROR cinder.api.middleware.fault [req-4db4e151-64fa-4cc9-954f-4b6a2612d89a 9d9c42986b7144cbb042e9485218c577 490892f61a00485e989e3b2e5ca96ab4 - - -] Caught error: <type 'exceptions.AttributeError'> 'UnityDriver' object has no attribute 'accept_transfer'

**Comment by peter-wangxu** [comment]
Unity needs to support `accept_transfer` by inheriting the `driver.TransferVD` from cinder

This feature is missed for Unity **Kilo**, **Liberty**, **Mitaka**, **Newton**.

**Comment by peter-wangxu** [comment]
@lucker6666 If you verified the fix, could you please provide the result here?

**Comment by lucker6666** [comment]
Verified, the issue was fixed.
