### ISSUE TITLE
_LE, _LI import error and missing attribute AddFCZone and RemoveFCZone

### ISSUE THREAD

**Issue by SiksAk** [emc-openstack/unity-cinder-driver#7]
Hi,

I found some code change needed for this driver due to recent cinder update:

1. [cinder/i18n.py](https://github.com/openstack/cinder/commit/a55a6b5c717c0802288ab802a8fbff287a4b6b66#diff-9260f9b1900374b200d97b6e904fae23) _LE, _LI has been removed.
There is an import error at [line 24 cinder/volume/drivers/dell_emc/unity/adapter.py](https://github.com/emc-openstack/unity-cinder-driver/blob/newton/cinder/volume/drivers/dell_emc/unity/adapter.py#L24)

2. [cinder/zonemanager/utils.py](https://github.com/openstack/cinder/commit/e79f5f702c3a7964e21dd1b86a70c9a8feddb170#diff-fdb112a17c44b660baed6edfd1c7dc48) Rename AddFCZone and RemoveFCZone to add_fc_zone and remove_fc_zone
Two errors at [line 122](https://github.com/emc-openstack/unity-cinder-driver/blob/newton/cinder/volume/drivers/dell_emc/unity/driver.py#L122) and [line 162](https://github.com/emc-openstack/unity-cinder-driver/blob/newton/cinder/volume/drivers/dell_emc/unity/driver.py#L162) cinder/volume/drivers/dell_emc/unity/driver.py

**Comment by peter-wangxu** [comment]
Hi @SiksAk 
Are you trying the newton unity driver on master cinder?

Thanks
Peter

**Comment by SiksAk** [comment]
Yes. We're working on test automation for this driver. And we work with devstack.

**Comment by SiksAk** [comment]
When will you create a new branch for ocata or pike? I could send a pull request for this with [my fix](https://github.com/SiksAk/unity-cinder-driver/commit/a0b502f7fca3bad9f7c52c50739b7b8a1efc05e6)

**Comment by peter-wangxu** [comment]
Hi @SiksAk 

We have unity driver merged for both `ocata` and `pika` on https://github.com/openstack/cinder.

You can use `stable/ocata` branch for ocata devstack, `master` for latest devstack.

Thanks
Peter

**Comment by SiksAk** [comment]
@peter-wangxu Thanks for your answer. Does this mean you won't update this repo anymore? Users only needs to follow up the cinder repo.

**Comment by peter-wangxu** [comment]
@SiksAk We keep posting any fix/feature to emc-openstack if the fix/feature are not able to be merged in upstream OpenStack(cinder/manila .etc). 
Unity cinder driver was firstly introduced in OpenStack cinder `ocata` release, so the `newton` branch in emc-openstack is the case: we don't have unity driver in Cinder/`newton` release, so we have `newton` branch in downstream emc-openstack to support customer's `newton` deployment.

For your 2nd question, user should use cinder repo for release after `newton`.

**Comment by SiksAk** [comment]
@peter-wangxu Cool. Really helpful information... Thanks again...
